# Generated by Django 4.1.7 on 2023-08-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_admin', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='h_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=30)),
                ('pc_number', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='s_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=30)),
                ('pc_number', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=200)),
            ],
        ),
    ]
